theme: jekyll-theme-hacker
title: How to Setup Github for Beginner💻
author: Miftah Ahmad Choiri
description: Just getting started with GitHub? I’ve put together a step-by-step guide to help beginners create a GitHub account, initialize a repository, and start managing their code with version control.